#!/bin/bash

# BUILD SCRIPT FOR BILITY
#   Downloads, installs, and completes setup of any dependencies
#   for this container / instance
# Written by Aaron Vontell (v0.0.2 - June 29, 2018)

# Env variables for env config
ANDROID_SDK=/Users/vontell/Library/Android/sdk
ADB=/Users/vontell/Library/Android/sdk/platform-tools
NDK=/Users/vontell/Library/Android/sdk/ndk-bundle
EM=/Users/vontell/Library/Android/sdk/tools/emulator

MINICAP_REPO=git@github.com:openstf/minicap.git

# TODO: Also install Android, Emulators, Kotlin, Gradle, Maven Repo, server deps, etc
#       i.e. this script is the container setup, should eventually belong in a Dockerfile

# Export for other scripts
export PATH=$PATH:$NDK:$ADB

rm -rf build.log
touch build.log

# First, download dependencies
if [ ! -d "dependencies/" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir dependencies
fi

if [ ! -d "dependencies/minicap" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  echo Installing Minicap... this make take a minute
  cd dependencies
  git clone $MINICAP_REPO minicap
  cd minicap
  git submodule init
  git submodule update
  ndk-build -C .
  cd ../../
fi
echo Minicap setup!

cd dependencies/minicap/example/

if [ ! -d "node_modules" ]; then
        echo "Installing node modules"
        npm install
fi
echo Node modules installed

echo Build finished!
exit 0